sonar.projectKey=go-backend-test
sonar.projectName=Go Backend Test
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,vendor/**
sonar.coverageReportPaths=coverage.xml