sonar.projectVersion=1.0.0
sonar.projectKey=go-backend-test
sonar.projectName=Go Backend Test
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,vendor/**,bin/**,reports/**,coverage.out,coverage.xml,.scannerwork/**
sonar.coverageReportPaths=coverage.xml
sonar.scm.exclusions.disabled=true