sonar.projectKey=go-backend-test
sonar.projectName=Go Backend Test
sonar.projectVersion=1.0.0
sonar.sources=main.go
sonar.tests=main_test.go
sonar.test.inclusions=**/*_test.go
sonar.exclusions=vendor/**,bin/**,reports/**,coverage.out,coverage.xml,.scannerwork/**,scripts/**,*.html,*.xml,*.sum,*.mod
sonar.coverageReportPaths=coverage.xml
sonar.scm.exclusions.disabled=true